spring:
  application:
    name: team3-backend-batch

  profiles:
    include: db, secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  batch:
    job:
      enabled: false

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.team3backendbatch
  configuration:
    map-underscore-to-camel-case: true

jwt:
  expiration: 1800000
  refresh-expiration: 604800000

batch:
  schedule:
    enabled: false
    zone: Asia/Seoul
    quantitative-cron: 0 0 1 * * *
    score-cron: 0 30 1 * * *
    promotion-cron: 0 0 2 * * *